spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888

#  Security Configurations:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9098/realms/e-commerce-micro-service/protocol/openid-connect/certs
          issuer-uri: http://localhost:9098/realms/e-commerce-micro-service